version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: medvedev/lara8-php73
    container_name: appudemylara8php73
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: medvedev/nginx-lara
    container_name: webserverudemylara8php73
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:5.7.36
    container_name: dbudemylara8php73mysql5736
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '42333:3306'
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redisudemylara8php73
    restart: unless-stopped


volumes:
  dbdata:
    driver: local

